### ISSUE TITLE
No enum match for: query

### ISSUE THREAD

**Issue by neuneuraxis** [AtomLinter/linter-swagger#49]
Hi

I have yaml file with this declaration:
  ```
...
delete:
      summary: some text
      tags:
        - test
      parameters:
        - name: start
          in: query
          description: toto
          required: true
          schema:
            type: string
            format: date-time
        - name: end
          in: query
          description: tata
          required: true
          schema:
            type: string
            format: date-time
...
```
And I have this 
```
Error      SwaggerParser     No enum match for: query     83:11
Error      SwaggerParser     No enum match for: query     90:11
```
In specification the value query is acceptable. In another yaml file, I have not this problem.

Thx
